version: "3.8"

services:
  api:
    build: .
    volumes:
      - .:/app 
    container_name: spacex_api
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:8.2.1-alpine
    container_name: spacex_redis
    ports:
      - "6379:6379"
